### ISSUE TITLE
global.namespace.truelicense.api.LicenseManagementException: java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by nikolakurtic** [christian-schlichtherle/truelicense#10] opened 2020-03-02 16:53 UTC
Hi,
upgrading some project to latest TrueLicense lib and I got this while installing license:
`global.namespace.truelicense.api.LicenseManagementException: java.lang.NoSuchMethodException: <unbound>=Class.valueOf("MULTI")`

There's a Enum class with this value.
Installing is done the same way as in other projects except this license has this custom field.

**Comment by christian-schlichtherle** [comment] 2020-03-02 18:11
Are you using code obfuscation? Overly aggressive ProGuard settings can break enum code. You can use the TrueLicense Maven Archetype to generate a sample project and then copy its ProGuard configuration to your project.

**Comment by nikolakurtic** [comment] 2020-03-03 08:07
I didn' use obfuscation.

**Comment by christian-schlichtherle** [comment] 2020-03-03 08:13
With the little information given, I cannot reproduce the issue. Also, as you said there is no MULTI enum in TrueLicense. Please provide more information to reproduce the issue.

**Comment by christian-schlichtherle** [comment] 2020-03-12 12:07
Will you be providing more information or can I close this issue?

**Comment by nikolakurtic** [comment] 2020-03-12 12:33
It was my fault, issue can be closed, thanks!

**Comment by christian-schlichtherle** [comment] 2020-03-12 12:34
No worries.

**Closed as completed by christian-schlichtherle** 2020-03-12 12:34 UTC
